### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by hanecak** [soit-sk/trademarks_-_upv_sk#1]
Scraper nejake udaje aj nazbiera, ale nakoniec skonci s:

No data for id 303739
No data for id 303799
Traceback (most recent call last):
  File "/repo/scraper.py", line 94, in <module>
    value = tds[2].text_content()
IndexError: list index out of range

**Comment by hanecak** [comment]
Info od Shady, ako to asi opravit:

treba pridat podmienku pre taketo pripady
http://registre.indprop.gov.sk/registre/detail/popup.do?register=oz&puv_id=304722
( ten posledny row nema dostatok td, takze to sfailuje )

if len(tds) > 2:
alebo tak by to malo byt

**Comment by katkad** [comment]
scraper veselo bezi dalej, takze fixored https://morph.io/soit-sk/trademarks_-_upv_sk
