### ISSUE TITLE
Last run failed 2 months ago with status code 137.

### ISSUE THREAD

**Issue by hanecak** [soit-sk/trademarks_-_upv_sk#2]
Scraper naposledy zbehol 4.7.2015 s tym, ze Morph.io hlasi ukoncenie s chybou:

```
Last run failed 2 months ago with status code 137.
```

Z vystupu vyberam:

```
Injecting configuration and compiling...
Injecting scraper and running...
Start or continue from id:  1
No data for id 1
...
No data for id 173189
No data for id 173190
```

Celkovop to teda vyzera o.i. aj na to, ze sa zmenil vstupny format a scraper uz nevie vytazit pozadovane udaje.

**Comment by katkad** [comment]
vie vytazit data kedze
69927 records added, 69926 records removed in the database

scraper skonci, lebo
Stopping scraper because it has run longer than 1 day

co je popisane v dokumentacii k morph.io

No data for id 173190
je normalne chovanie scrapera, aby sme videli kde sa asi nachadza
